name: CI pipeline
on: [push] # Run it from the UI.
env:
  DOCKER_USERNAME: 'samson84cc'
  DOCKER_REPO: 'animal-shelter'
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{github.sha}} .
      - name: Lint
        run: docker run ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{github.sha}} python -m pylint .
      - name: Test
        run: docker run ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{github.sha}} python -m pytest tests
      - name: Docker Login
        uses: docker/login-action@v3
        with: 
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{github.sha}}

